export const METHOD_LABELS: Record<string, string> = {
  telegram_stars: 'Telegram Stars',
  tribute: 'Tribute',
  cryptobot: 'CryptoBot',
  heleket: 'Heleket',
  yookassa: 'YooKassa',
  mulenpay: 'MulenPay',
  pal24: 'PayPalych',
  platega: 'Platega',
  wata: 'WATA',
  freekassa: 'Freekassa',
  freekassa_sbp: 'Freekassa СБП',
  freekassa_card: 'Freekassa Карта',
  cloudpayments: 'CloudPayments',
  kassa_ai: 'Kassa AI',
  riopay: 'RioPay',
  severpay: 'SeverPay',
  paypear: 'PayPear',
  rollypay: 'RollyPay',
  aurapay: 'AuraPay',
  overpay: 'OverPay',
  etoplatezhi: 'Etoplatezhi',
  antilopay: 'Antilopay',
  jupiter: 'Jupiter',
  cispay: 'CisPay',
  tabpay: 'TabPay',
  paritypay: 'ParityPay',
  donut: 'Donut',
  lava: 'Lava',
  apple_iap: 'Apple In-App Purchase',
  manual: 'Ручное пополнение',
};
